In [1]:
import os
import pandas as pd

In [2]:
from aq_data_preprocess import aq_data_preprocess

In [3]:
aq_data_preprocess(city='bj')

(11602, 210)

In [4]:
aq_data_preprocess(city='ld')

/home/cvdev/tf/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2963: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/home/cvdev/air-quality-prediction/aq_data_preprocess.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_merged.loc[hour] = for_row + (for_step/all_steps) * delata_values
/home/cvdev/air-quality-prediction/aq_data_preprocess.py:210: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_merged.loc[hour] = nan_series
/home/cvdev/air-quality-prediction/aq_data_preprocess.py:212: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_merged.sort_index(inplace=True)

(11616, 39)

In [5]:
from weather_data_preprocess import meo_data_preprocess

In [2]:
meo_data_preprocess(city='bj')

将要保存的天气数据的尺寸是　 (11592, 175)

In [6]:
meo_data_preprocess(city='ld')

名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
将要保存的天气数据的尺寸是　 (11616, 120)

In [1]:
from utils.weather_data_util import load_ld_grid_meo_data

In [2]:
ld_near_stations = {'BL0': 'london_grid_409',
 'BX1': 'london_grid_472',
 'BX9': 'london_grid_472',
 'CD1': 'london_grid_388',
 'CD9': 'london_grid_409',
 'CR8': 'london_grid_408',
 'CT2': 'london_grid_409',
 'CT3': 'london_grid_409',
 'GB0': 'london_grid_451',
 'GN0': 'london_grid_451',
 'GN3': 'london_grid_451',
 'GR4': 'london_grid_451',
 'GR9': 'london_grid_430',
 'HR1': 'london_grid_368',
 'HV1': 'london_grid_472',
 'KC1': 'london_grid_388',
 'KF1': 'london_grid_388',
 'LH0': 'london_grid_346',
 'LW2': 'london_grid_430',
 'MY7': 'london_grid_388',
 'RB7': 'london_grid_452',
 'ST5': 'london_grid_408',
 'TD5': 'london_grid_366',
 'TH4': 'london_grid_430'}

In [3]:
bj_grid_meo_dataset, stations, bj_meo_stations = load_ld_grid_meo_data(ld_near_stations)

名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')
名字 Index(['humidity', 'pressure', 'temperature', 'wind_direction', 'wind_speed'], dtype='object')

In [4]:
bj_meo_stations['CD1']

,CD1_humidity,CD1_pressure,CD1_temperature,CD1_wind_direction,CD1_wind_speed
time,,,,,
2018-04-03 00:00:00,96.00,990.8283,8.72,196.47,14.57
2018-04-03 01:00:00,95.00,990.5847,8.96,197.24,15.10
2018-04-03 02:00:00,94.00,990.3389,9.31,196.92,15.97
2018-04-03 03:00:00,92.00,990.1236,9.63,196.03,17.07
2018-04-03 04:00:00,91.00,990.0427,9.85,192.78,18.00
2018-04-03 05:00:00,89.00,989.8766,9.94,193.95,18.70
2018-04-03 06:00:00,86.00,992.8257,10.25,197.21,16.69
2018-04-03 07:00:00,88.00,989.7941,10.06,198.31,19.24
2018-04-03 08:00:00,84.00,992.9618,10.46,200.85,16.43
2018-04-03 09:00:00,84.00,990.1671,10.92,204.51,20.22
2018-04-03 10:00:00,79.00,990.4957,11.66,205.05,21.07
2018-04-03 11:00:00,71.00,990.6286,12.77,207.77,22.87
2018-04-03 12:00:00,64.00,990.6993,13.63,209.90,24.23
2018-04-03 13:00:00,59.00,990.7087,13.95,211.44,24.57
2018-04-03 14:00:00,57.00,990.6842,13.81,212.30,24.05
2018-04-03 15:00:00,57.00,990.6599,13.43,212.16,23.03
2018-04-03 16:00:00,60.00,990.7102,12.62,211.24,22.79
2018-04-03 17:00:00,64.00,990.8639,12.08,209.12,22.02
2018-04-03 18:00:00,68.00,991.0736,11.51,206.34,21.14
2018-04-03 19:00:00,72.00,991.3145,10.93,203.17,20.06
2018-04-03 20:00:00,75.00,991.5532,10.37,199.73,18.74
2018-04-03 21:00:00,71.00,994.7709,11.35,199.21,18.28
2018-04-03 22:00:00,78.00,995.0544,10.61,191.99,15.56
2018-04-03 23:00:00,86.00,992.0753,9.00,184.63,14.78
2018-04-12 00:00:00,90.00,1001.4103,9.61,45.95,8.67
2018-04-12 01:00:00,90.00,1000.9911,9.48,39.54,8.83
2018-04-12 02:00:00,89.00,1000.6263,9.35,31.84,9.17
2018-04-12 03:00:00,89.00,1000.3002,9.18,24.90,9.54
2018-04-12 05:00:00,88.00,999.9639,7.83,18.08,10.85
2018-04-12 08:00:00,88.00,999.3706,8.60,17.18,9.79
...,...,...,...,...,...
2018-03-27 00:00:00,68.73,1010.2200,7.42,199.92,11.37
2018-03-27 01:00:00,69.63,1009.2200,7.31,191.73,12.66
2018-03-27 02:00:00,70.54,1008.2300,7.20,185.17,14.16
2018-03-27 03:00:00,71.45,1007.2300,7.09,179.92,15.81
2018-03-27 04:00:00,75.97,1006.0100,7.05,176.97,17.41
2018-03-27 05:00:00,80.49,1004.7800,7.01,174.53,19.05
2018-04-11 00:00:00,88.00,1002.2919,10.29,51.22,10.09
2018-04-11 01:00:00,89.00,1002.1549,10.11,46.57,9.23
2018-04-11 02:00:00,91.00,1002.0133,9.95,42.58,8.45
2018-04-11 03:00:00,92.00,1001.9596,9.84,38.68,7.83
2018-04-11 04:00:00,91.00,1001.9439,9.63,16.45,7.53
2018-04-11 05:00:00,91.00,1002.1236,9.45,18.32,8.22
2018-04-11 06:00:00,90.00,1002.3159,9.18,21.75,9.16
2018-04-11 07:00:00,89.00,1002.4524,8.82,24.60,10.11
2018-04-11 08:00:00,88.00,1002.5552,8.61,27.74,10.67
2018-04-11 09:00:00,79.00,1005.7314,9.40,31.71,8.88
2018-04-11 10:00:00,76.00,1003.4260,9.67,43.12,10.16
2018-04-11 11:00:00,70.00,1003.3261,11.68,57.26,9.31
2018-04-11 12:00:00,65.00,1003.0765,13.56,68.11,9.18
2018-04-11 13:00:00,61.00,1002.7164,14.75,68.92,9.57
2018-04-11 14:00:00,59.00,1002.3115,15.26,64.10,10.19
2018-04-11 15:00:00,59.00,1001.9343,15.28,59.90,10.85
2018-04-11 16:00:00,67.00,1002.2801,12.87,44.18,10.19
2018-04-11 17:00:00,71.00,1002.0214,12.44,47.62,10.08
2018-04-11 18:00:00,76.00,1001.8702,12.00,54.57,9.80
2018-04-11 19:00:00,82.00,1001.8863,11.47,63.09,9.55
2018-04-11 20:00:00,80.00,1004.9985,12.34,76.04,8.74
2018-04-11 21:00:00,90.00,1002.0185,10.48,74.18,9.16
2018-04-11 22:00:00,87.00,1002.2619,10.03,50.59,8.73
2018-04-11 23:00:00,89.00,1001.8732,9.78,49.27,8.65

In [16]:
import pandas as pd

In [8]:
pd.read_csv("./test/bj_aq_describe.csv")

,Unnamed: 0,wanshouxigong_aq_PM2.5,wanshouxigong_aq_PM10,wanshouxigong_aq_NO2,wanshouxigong_aq_CO,wanshouxigong_aq_O3,wanshouxigong_aq_SO2,huairou_aq_PM2.5,huairou_aq_PM10,huairou_aq_NO2,...,tongzhou_aq_NO2,tongzhou_aq_CO,tongzhou_aq_O3,tongzhou_aq_SO2,shunyi_aq_PM2.5,shunyi_aq_PM10,shunyi_aq_NO2,shunyi_aq_CO,shunyi_aq_O3,shunyi_aq_SO2
0,count,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,...,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.000000,10991.00000,10991.000000,10991.000000
1,mean,62.271722,97.358066,49.279137,0.928801,52.018288,8.645119,51.313211,81.286507,27.489082,...,51.309935,0.948540,57.967837,11.301974,58.696843,88.204758,42.358202,0.94475,61.108407,9.512283
2,std,67.707743,102.020944,31.397640,0.893754,49.422676,10.867185,57.758924,101.016169,22.254528,...,33.615150,0.979783,55.805430,13.375042,65.778163,101.042981,30.678728,0.93686,54.746680,11.401270
3,min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
4,25%,17.000000,38.000000,24.000000,0.400000,10.000000,2.000000,13.000000,27.000000,10.000000,...,23.000000,0.400000,10.000000,2.000000,14.000000,30.000000,17.000000,0.40000,16.000000,2.000000
5,50%,43.000000,75.000000,43.000000,0.700000,44.000000,4.000000,32.000000,56.000000,21.000000,...,45.000000,0.700000,49.000000,7.000000,37.000000,66.750000,37.000000,0.70000,54.000000,6.000000
6,75%,82.000000,126.000000,70.000000,1.200000,73.000000,11.000000,71.000000,107.000000,39.000000,...,74.000000,1.200000,83.000000,15.000000,80.000000,115.100000,63.000000,1.20000,85.000000,12.000000
7,max,823.000000,2262.000000,257.000000,12.100000,346.000000,189.000000,1574.000000,3000.000000,174.000000,...,258.000000,11.600000,500.000000,264.000000,762.000000,3000.000000,258.000000,13.30000,417.000000,262.000000

In [8]:
from seq2seq.seq2seq_data_util import generate_X_test_set, generate_dev_set

In [9]:
bj_station_list = ['dongsi_aq','tiantan_aq','guanyuan_aq','wanshouxigong_aq','aotizhongxin_aq',
            'nongzhanguan_aq','wanliu_aq','beibuxinqu_aq','zhiwuyuan_aq','fengtaihuayuan_aq',
            'yungang_aq','gucheng_aq','fangshan_aq','daxing_aq','yizhuang_aq','tongzhou_aq',
            'shunyi_aq','pingchang_aq','mentougou_aq','pinggu_aq','huairou_aq','miyun_aq',
            'yanqin_aq','dingling_aq','badaling_aq','miyunshuiku_aq','donggaocun_aq',
            'yongledian_aq','yufa_aq','liulihe_aq','qianmen_aq','yongdingmennei_aq',
            'xizhimenbei_aq','nansanhuan_aq','dongsihuan_aq']            
bj_X_aq_list = ["PM2.5","PM10","O3","CO","SO2","NO2"]  
bj_y_aq_list = ["PM2.5","PM10","O3"]
bj_X_meo_list = ["temperature","pressure","humidity","direction","speed"]

In [10]:
station_list = bj_station_list
X_aq_list = bj_X_aq_list
y_aq_list = bj_y_aq_list
X_meo_list = bj_X_meo_list

In [11]:
X_predict = generate_X_test_set(city="bj",
                             station_list=station_list,
                             X_aq_list=X_aq_list,
                             X_meo_list=X_meo_list,
                             pre_days=5,
                             gap=0)

695
576

In [17]:
pd.isnull(X_predict)

array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]]])

In [13]:
test_x, test_y = generate_dev_set(city='bj',
                                  station_list=station_list,
                                  X_aq_list=X_aq_list, 
                                  y_aq_list=y_aq_list, 
                                  X_meo_list=X_meo_list,
                                  pre_days=5,
                                  gap=0)

In [14]:
test_x.shape

(20, 120, 385)